

export const ADDRESS_REQUEST = "ADDRESS_REQUEST";
export const ADDRESS_POST_SUCCESS = "ADDRESS_POST_SUCCESS";
export const ADDRESS_FAILURE = "ADDRESS_FAILURE";

export const ADDRESS_GET_SUCCESS = "ADDRESSGETSUCCESS";

