

export const CARTREQUEST = "CARTREQUEST";
export const CARTPOSTSUCCESS = "CARTSUCCESS";
export const CARTFAILURE = "CARTFAILURE";

export const CARTGETSUCCESS = "CARTGETSUCCESS";

export const CARTDELETESUCCESS = "CARTDELETESUCCESS";
